info:
  name: Query All
  type: http
  seq: 2

http:
  method: GET
  url: "{{protocol}}://{{hostname}}:{{ticketmaster_port}}/api/ticketmaster/ticket/:ticket-id/task"
  params:
    - name: ticket-id
      value: "70"
      type: path
  body:
    type: multipart-form
    data:
      - name: task
        type: text
        value: |-
          {
                  "title": "sample task",
                  "notes": "blabla notes here",
                  "due_at": { "seconds": 1766875660 },
                  "type": 1,
                  "status": 1,
                  "assigned_user_ids": [22, 51]
              }
      - name: file_descriptions
        type: text
        value: f1
      - name: file_descriptions
        type: text
        value: f2
      - name: files
        type: file
        value:
          - /C:/Users/dyson/Desktop/1.png
      - name: files
        type: file
        value:
          - /C:/Users/dyson/Desktop/2.png
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
