info:
  name: Subscribe
  type: http
  seq: 6

http:
  method: POST
  url: "{{protocol}}://{{hostname}}:{{ticketmaster_port}}/api/ticketmaster/ticket/:ticket-id/task/:task-id/subscribe"
  params:
    - name: ticket-id
      value: "17"
      type: path
    - name: task-id
      value: "3"
      type: path
  body:
    type: json
    data: "{\r\n    \"subscribe\": false\r\n}"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
